import {prototypeStorage} from './prototype-storage.mjs';
import {instantiateFavorite,createFolder,moveFolder,removeFolder,reusableScene} from './node-library-state.mjs';
export function libraryContent(){const root=document.createElement('div');root.className='tool-content library-content';root.innerHTML=`<div class="library-tabs" role="tablist" aria-label="Kütüphane bölümleri"><button role="tab" aria-selected="true" data-source="builtin">Hazır paketler</button><button role="tab" aria-selected="false" data-source="user">Benim düğümlerim</button></div><div class="library-categories" hidden></div><div class="library-path"></div><div class="library-toolbar"><input class="library-search" type="search" placeholder="Bu klasörde ara…" aria-label="Düğüm kütüphanesinde ara"><button class="author-button" data-folder-new hidden>+ Klasör</button></div><p class="library-description"></p><div class="library-list"></div><p class="library-empty" hidden></p>`;return root;}
const validItem=item=>typeof item?.id==='string'&&typeof item.scene?.title==='string'&&item.scene?.objects&&['moon','character','dialogue'].every(key=>item.scene.objects[key]&&['x','y','w','h'].every(field=>Number.isFinite(item.scene.objects[key][field]))&&(!item.scene.objects[key].components||Array.isArray(item.scene.objects[key].components)&&item.scene.objects[key].components.every(c=>c&&typeof c.type==='string'&&c.values&&typeof c.values==='object')));
export function bindLibrary(panel,inspector,context){
  let items=[],folders=[],source='builtin',folderId=null,packageOpen=false,query='';
  try{const stored=JSON.parse(prototypeStorage.getItem('rowl-user-node-library'));if(stored){items=Array.isArray(stored.items)?stored.items.filter(validItem):[];if(Array.isArray(stored.folders)){let pending=stored.folders.filter(f=>typeof f?.id==='string'&&typeof f.name==='string'&&(f.parentId===null||typeof f.parentId==='string')).slice(0,1000);for(let pass=0;pending.length&&pass<1000;pass++){const rest=[];for(const f of pending){if(f.parentId&&!folders.some(parent=>parent.id===f.parentId)){rest.push(f);continue;}try{folders=createFolder(folders,f.name,f.parentId,f.id);}catch{}}if(rest.length===pending.length)break;pending=rest;}}}else{const legacy=JSON.parse(prototypeStorage.getItem('rowl-node-favorites'));if(Array.isArray(legacy))items=legacy.filter(validItem).map(item=>({...item,folderId:null}));}}catch{}
  items=items.map(item=>({...item,folderId:folders.some(f=>f.id===item.folderId)?item.folderId:null}));
  const list=panel.querySelector('.library-list'),empty=panel.querySelector('.library-empty'),path=panel.querySelector('.library-path');
  const dialog=document.createElement('dialog');dialog.id='library-dialog';dialog.setAttribute('aria-labelledby','library-dialog-title');document.body.append(dialog);let opener;
  dialog.addEventListener('close',()=>{if(opener?.isConnected)opener.focus({preventScroll:true});else panel.querySelector('[data-source="user"]').focus({preventScroll:true});});
  function form(title,description,primary,submit){opener=document.activeElement;dialog.replaceChildren();const form=document.createElement('form'),heading=document.createElement('h2'),text=document.createElement('p'),body=document.createElement('div'),footer=document.createElement('footer');heading.id='library-dialog-title';heading.textContent=title;text.textContent=description;body.className='library-dialog-fields';footer.className='author-footer';const cancel=document.createElement('button');cancel.type='button';cancel.className='author-button';cancel.textContent='Vazgeç';cancel.onclick=()=>dialog.close();const confirm=document.createElement('button');confirm.className='primary-button';confirm.textContent=primary;const error=document.createElement('p');error.className='author-error';error.setAttribute('role','alert');footer.append(cancel,confirm);form.append(heading,text,body,error,footer);form.onsubmit=event=>{event.preventDefault();try{submit(new FormData(form));dialog.close();}catch(e){error.textContent=e.message;}};dialog.append(form);dialog.showModal();return body;}
  function input(body,labelText,name,value,multiline=false){const label=document.createElement('label');label.className='author-field';label.textContent=labelText;const input=document.createElement(multiline?'textarea':'input');input.name=name;input.value=value;input.required=true;input.maxLength=multiline?2000:80;label.append(input);body.append(label);return input;}
  function folderSelect(body,name,value,exclude=null){const label=document.createElement('label');label.className='author-field';label.textContent='Klasör';const select=document.createElement('select');select.name=name;for(const f of [{id:'',name:'Benim düğümlerim'},...folders.filter(f=>{let id=f.id;while(id){if(id===exclude)return false;id=folders.find(parent=>parent.id===id)?.parentId;}return true;}).sort((a,b)=>folderPath(a.id).localeCompare(folderPath(b.id),'tr'))]){const option=document.createElement('option');option.value=f.id;option.textContent=f.id?folderPath(f.id):f.name;select.append(option);}select.value=value??'';label.append(select);body.append(label);}
  function folderPath(id){const parts=[],seen=new Set();while(id&&!seen.has(id)){seen.add(id);const f=folders.find(f=>f.id===id);if(!f)break;parts.unshift(f.name);id=f.parentId;}return parts.join(' / ');}
  function confirmRemove(title,description,action){form(title,description,'Kaldır',()=>{action();persist();paint();updateBookmark();});}
  function removeItem(item){confirmRemove('Düğüm kısayolunu kaldır',`“${item.scene.title}” kütüphaneden kaldırılacak. Sahneye eklenmiş kopyalar korunur.`,()=>{items=items.filter(i=>i.id!==item.id);});}
  function removeFolderRecord(folder){confirmRemove('Klasörü kaldır',`“${folder.name}” klasörü kaldırılacak. İçindeki düğümler ve alt klasörler üst klasöre taşınacak.`,()=>{const next=removeFolder(folders,items,folder.id);folders=next.folders;items=next.items;if(folderId===folder.id)folderId=folder.parentId;});}
  function removeAction(body,label,action){const button=document.createElement('button');button.type='button';button.className='library-remove-action';button.textContent=label;button.onclick=action;body.append(button);}
  function editFolder(folder=null){const body=form(folder?'Klasörü yönet':'Yeni klasör','Düğümlerini klasörlerle düzenle.','Kaydet',data=>{const name=data.get('name'),parentId=data.get('parent')||null;folders=folder?moveFolder(folders,folder.id,parentId,name):createFolder(folders,name,parentId);folderId=folder?folder.id:folders[folders.length-1].id;persist();paint();updateBookmark();});input(body,'Klasör adı','name',folder?.name??'');folderSelect(body,'parent',folder?.parentId??folderId,folder?.id);if(folder)removeAction(body,'Klasörü kaldır…',()=>removeFolderRecord(folder));}
  function summary(scene){const objects=Object.values(scene.objects);return `${objects.length} obje · ${objects.reduce((count,object)=>count+(object.components?.length??0),0)} bileşen`;}
  function editItem(item){const body=form('Düğüm kaydını yönet','İsim ve klasörü buradan değiştir. İçeriği güncellemek için düğümün Inspector’ını kullan.','Kaydet',data=>{const title=data.get('title').trim();if(!title)throw Error('Ad boş bırakılamaz.');items=items.map(i=>i.id===item.id?{...i,scene:{...structuredClone(i.scene),title},folderId:data.get('folder')||null}:i);folderId=data.get('folder')||null;persist();paint();updateBookmark();});input(body,'Kayıt adı','title',item.scene.title);folderSelect(body,'folder',item.folderId);
    const preview=document.createElement('details'),heading=document.createElement('summary'),tree=document.createElement('ul');preview.className='library-snapshot';heading.textContent=`Kaydedilen hiyerarşi · ${summary(item.scene)}`;preview.append(heading,tree);
    for(const [id,object] of Object.entries(item.scene.objects)){const entry=document.createElement('li'),name=document.createElement('strong'),properties=document.createElement('span');name.textContent={moon:'Ay',character:'Karakter',dialogue:'Diyalog'}[id]??id;properties.textContent=`X: ${object.x} · Y: ${object.y} · ${object.w} × ${object.h} · ${object.visible===false?'Gizli':'Görünür'}`;entry.append(name,properties);for(const component of object.components??[]){const line=document.createElement('span');line.textContent=`${component.type}: ${Object.entries(component.values).map(([key,value])=>`${key} = ${typeof value==='object'?JSON.stringify(value):value}`).join(' · ')}`;entry.append(line);}tree.append(entry);}body.append(preview);removeAction(body,'Kütüphane kaydını kaldır…',()=>removeItem(item));
  }
  function smallButton(row,label,text,action){const button=document.createElement('button');button.className='library-item-action';button.textContent=text;button.setAttribute('aria-label',label);button.title=label;button.onclick=action;row.append(button);}
  function row(name,description,icon,action){const row=document.createElement('div');row.className='library-row';const main=document.createElement('button');main.className='library-add';main.innerHTML=`<svg aria-hidden="true"><use href="#i-${icon}"/></svg><span><strong></strong><small></small></span>`;main.querySelector('strong').textContent=name;main.querySelector('small').textContent=description;main.onclick=action;row.append(main);list.append(row);return row;}
  const expandedFolders=new Set();
  function navigateFolder(id){folderId=id;query='';panel.querySelector('input').value='';let parent=id;while(parent){expandedFolders.add(parent);parent=folders.find(f=>f.id===parent)?.parentId;}paint();}
  function paintCategories(){
    const categories=panel.querySelector('.library-categories');categories.hidden=source!=='user';categories.replaceChildren();if(source!=='user')return;
    const header=document.createElement('div');header.className='library-category-heading';header.textContent='KLASÖRLER';categories.append(header);
    function branch(folder,depth){
      const id=folder?.id??null,children=folders.filter(f=>f.parentId===id),row=document.createElement('div');row.className='library-category-row';row.style.setProperty('--depth',depth);row.setAttribute('role','treeitem');row.setAttribute('aria-selected',String(folderId===id));row.setAttribute('aria-level',String(depth+1));
      if(children.length){row.setAttribute('aria-expanded',String(!id||expandedFolders.has(id)));const toggle=document.createElement('button');toggle.className='library-category-toggle';toggle.textContent=!id||expandedFolders.has(id)?'⌄':'›';toggle.setAttribute('aria-label',`${folder?.name??'Benim düğümlerim'} alt klasörlerini ${expandedFolders.has(id)||!id?'daralt':'aç'}`);toggle.onclick=()=>{if(!id)return;if(expandedFolders.has(id))expandedFolders.delete(id);else expandedFolders.add(id);paintCategories();};if(!id)toggle.disabled=true;row.append(toggle);}else{const spacer=document.createElement('span');spacer.className='library-category-toggle';row.append(spacer);}
      const open=document.createElement('button');open.className='library-category-name';open.textContent=folder?.name??'Benim düğümlerim';open.setAttribute('aria-label',`${folder?folderPath(id):'Benim düğümlerim'} klasörünü aç`);open.onclick=()=>navigateFolder(id);const count=document.createElement('span');count.className='library-category-count';count.textContent=items.filter(i=>i.folderId===id).length;count.title=`${count.textContent} düğüm`;count.setAttribute('aria-label',`${count.textContent} düğüm`);row.append(open,count);if(folder)smallButton(row,`${folderPath(id)} klasörünü yönet`,'…',()=>editFolder(folder));categories.append(row);
      if(!id||expandedFolders.has(id))children.forEach(child=>branch(child,depth+1));
    }
    categories.setAttribute('role','tree');categories.setAttribute('aria-label','Kullanıcı klasörleri');branch(null,0);
  }
  function paint(){
    let ancestor=folderId;while(ancestor){expandedFolders.add(ancestor);ancestor=folders.find(f=>f.id===ancestor)?.parentId;}
    list.replaceChildren();path.replaceChildren();paintCategories();panel.querySelectorAll('[data-source]').forEach(el=>el.setAttribute('aria-selected',String(el.dataset.source===source)));panel.querySelector('[data-folder-new]').hidden=source!=='user';
    const root=document.createElement('button');root.className='library-crumb';root.textContent=source==='builtin'?'Hazır paketler':'Benim düğümlerim';root.onclick=()=>{folderId=null;packageOpen=false;query='';panel.querySelector('input').value='';paint();};path.append(root);
    if(source==='user'&&folderId){const lineage=[];let id=folderId;while(id){const f=folders.find(f=>f.id===id);if(!f)break;lineage.unshift(f);id=f.parentId;}for(const f of lineage){const button=document.createElement('button');button.className='library-crumb';button.textContent=`/ ${f.name}`;button.onclick=()=>{folderId=f.id;query='';panel.querySelector('input').value='';paint();};path.append(button);}}
    if(source==='builtin'&&packageOpen){const label=document.createElement('span');label.textContent='/ Rowl';path.append(label);}
    panel.querySelector('.library-description').textContent=source==='builtin'?'Salt okunur · Sahneye eklenen kopyayı düzenleyebilirsin.':'Düğümün tamamını Inspector’daki yıldızla kaydet.';
    const match=name=>name.toLocaleLowerCase('tr').includes(query);
    if(source==='builtin'){
      if(!packageOpen&&match('Rowl'))row('Rowl','Hazır paket · Salt okunur','assets',()=>{packageOpen=true;query='';panel.querySelector('input').value='';paint();});
      if(packageOpen&&match('Standart düğüm')){const r=row('Standart düğüm','Mevcut varsayılan düğüm · Ekle','node',()=>context.add());r.querySelector('button').setAttribute('aria-label','Standart düğümü ekle');}
    }else{
      for(const item of items.filter(i=>i.folderId===folderId&&match(i.scene.title))){const r=row(item.scene.title,`${summary(item.scene)} · Sahneye ekle`,'node',()=>context.add(instantiateFavorite(item,crypto.randomUUID())));r.querySelector('button').setAttribute('aria-label',`${item.scene.title} düğümünü ekle`);smallButton(r,`${item.scene.title} kaydını yönet`,'…',()=>editItem(item));}
    }
    empty.hidden=list.childElementCount>0;empty.textContent=query?'Bu klasörde eşleşme yok.':'Bu klasörde düğüm yok. Inspector’daki yıldızla buraya kaydet veya bir kaydı bu klasöre taşı.';
  }
  function persist(){try{prototypeStorage.setItem('rowl-user-node-library',JSON.stringify({folders,items}));}catch{context.notify('Kütüphane bu oturumda tutuluyor; tarayıcıya kaydedilemedi.');}}
  function saveScene(scene,existing=null){
    const body=form(existing?'Kütüphane kaydını güncelle':'Düğümü kütüphaneye kaydet','Düğümün tüm hiyerarşisi, obje konumları, görünürlükleri ve bileşen ayarları kaydedilir. Sahneye eklenmiş kopyalar değişmez.','Kaydet',data=>{
      const snapshot=reusableScene(scene);snapshot.title=data.get('title').trim();if(!snapshot.title)throw Error('Ad boş bırakılamaz.');
      const item={id:scene.id,scene:snapshot,folderId:data.get('folder')||null};items=existing?items.map(i=>i.id===existing.id?item:i):[...items,item];source='user';folderId=item.folderId;persist();paint();updateBookmark();context.notify('Düğümün tüm hiyerarşisi ve ayarları kaydedildi.');
    });input(body,'Kayıt adı','title',existing?.scene.title??scene.title);folderSelect(body,'folder',existing?.folderId??(source==='user'?folderId:null));
  }
  function updateBookmark(){
    const scene=context.selectedScene(),stored=items.find(item=>item.id===scene.id),star=inspector.querySelector('[data-library-star]');
    star.textContent=stored?'★ Kütüphaneden kaldır':'☆ Kütüphaneye kaydet';star.setAttribute('aria-pressed',String(!!stored));inspector.querySelector('[data-library-update]').hidden=!stored;
    inspector.querySelector('[data-library-status]').textContent=stored?`Kayıt: ${folderPath(stored.folderId)||'Benim düğümlerim'} / ${stored.scene.title}. Değişiklikleri kayda aktarmak için Kaydı güncelle’yi kullan.`:'Tüm hiyerarşi, obje özellikleri ve bileşen ayarları kaydedilir.';
  }
  inspector.querySelector('[data-library-star]').onclick=()=>{const scene=context.selectedScene(),stored=items.find(item=>item.id===scene.id);if(stored)removeItem(stored);else saveScene(scene);};
  inspector.querySelector('[data-library-update]').onclick=()=>{const scene=context.selectedScene();saveScene(scene,items.find(item=>item.id===scene.id));};
  panel.querySelectorAll('[data-source]').forEach(button=>button.onclick=()=>{source=button.dataset.source;folderId=null;packageOpen=false;query='';panel.querySelector('input').value='';paint();});panel.querySelector('[data-folder-new]').onclick=()=>editFolder();panel.querySelector('input').oninput=event=>{query=event.target.value.toLocaleLowerCase('tr');paint();};paint();return {update:updateBookmark};
}
