import {bindFormFeedback} from './design-status.js';
import {prototypeStorage} from './prototype-storage.mjs';
const categories=[['project','Proje','assets'],['game','Görüntü','game'],['story','Hikâye','story'],['audio','Ses','audio'],['input','Kontroller','input'],['save','Kayıt / dil','save'],['editor','Editör','inspector'],['export','Dışa aktar','export']];
const headings={project:['Proje ayarları','Hikâyenin kimliği','Oyuncunun ilk karşılaşacağı isim, kapak ve proje bilgileri.'],game:['Görüntü ve sahne','Sahneye bir çerçeve','Oyunun ekranını, oranını ve ilk sahnesini belirle.'],story:['Hikâye ve metin','Hikâyenin ritmi','Diyalogların okunma, ilerleme ve seçim biçimini tasarla.'],audio:['Ses ve müzik','Hikâyenin sesi','Müzik, efekt ve seslendirme arasında bir denge kur.'],input:['Kontroller','Oyuncunun dokunuşu','Klavye ve dokunmatik hareketleri aynı akışa bağla.'],save:['Kayıt ve dil','Kaldığın yerden','Kayıt düzeni, diller ve daha rahat okuma seçenekleri.'],editor:['Editör tercihleri','Sana ait çalışma alanı','Görünüm, yardımcı çizgiler ve çalışma alışkanlıkları.'],export:['Dışa aktarma','Paylaşmaya hazır','Hedefi ve paketin görünümünü seç; proje taslağını indir.']};
const defaults={project:'Bir gece, bir ışık',author:'Rowl Studio',version:'0.1.0',description:'Ay ışığında başlayan küçük bir yolculuk.',cover:'night',resolution:'1280x800',startScene:'selected',windowMode:'Pencere',scaleMode:'Oranı koru',background:'#101014',fps:'60',textSpeed:32,textSize:18,font:'Sade',autoAdvance:false,autoDelay:2,skip:'Yalnız okunmuş metin',choiceTimer:false,choiceSeconds:15,master:85,music:70,effects:80,voice:100,mute:false,backgroundAudio:false,fade:1,continueKey:'Enter / Boşluk',historyKey:'H',autoKey:'A',skipKey:'Ctrl',menuKey:'Esc',quickSaveKey:'F5',quickLoadKey:'F9',tap:true,swipe:true,hold:false,gamepad:false,language:'Türkçe',english:true,slots:12,autosave:true,savePoint:'Sahne geçişlerinde',history:100,largeText:false,reducedMotion:false,theme:'Gece',accent:'Kemik',grid:true,guides:true,snap:true,rulers:false,platform:'Windows',packageName:'Bir-gece-bir-isik',includeMusic:true,includeScripts:true,includeLanguages:true,compression:'Dengeli'};
const field=(key,label,type='text',extra='')=>`<label class="setting-field">${label}<input name="${key}" type="${type}" ${extra}></label>`;
const select=(key,label,options)=>`<label class="setting-field">${label}<select name="${key}">${options.map(item=>{const [value,text]=Array.isArray(item)?item:[item,item];return `<option value="${value}">${text}</option>`;}).join('')}</select></label>`;
const toggle=(key,title,description)=>`<label class="setting-toggle"><span><strong>${title}</strong><small>${description}</small></span><input name="${key}" type="checkbox"><i aria-hidden="true"></i></label>`;
const range=(key,title,min,max,step=1,suffix='%')=>`<label class="setting-range"><span>${title}<output data-output="${key}"></output></span><input name="${key}" type="range" min="${min}" max="${max}" step="${step}" data-suffix="${suffix}" aria-label="${title}"></label>`;
const card=(title,description,content)=>`<section class="settings-card"><header><h3>${title}</h3><p>${description}</p></header>${content}</section>`;
const sections={
  project:()=>`<div class="project-identity"><div class="project-cover" data-cover-preview><svg><use href="#i-moon"/></svg><span>ROWL / HİKÂYE</span></div><div><span class="tool-caption">PROJE KAPAĞI</span><strong data-project-preview></strong><p>Hikâyenin ilk izlenimi.</p>${select('cover','Kapak görünümü',[['night','Ay ışığı'],['dawn','Yeni bir sabah'],['forest','Orman yolu']])}</div></div><div class="settings-columns">${card('Kimlik','Oyun listesinde ve başlangıç ekranında görünen bilgiler.',`${field('project','Proje adı','text','maxlength="80" required')}${field('author','Yapımcı / stüdyo','text','maxlength="80"')}${field('version','Sürüm','text','maxlength="24"')}`)}${card('Hakkında','Hikâyeyi birkaç cümleyle anlat.',`<label class="setting-field">Kısa açıklama<textarea name="description" rows="5" maxlength="400"></textarea></label><div class="info-note"><svg><use href="#i-story"/></svg><span>3 sahne · 1 karakter · Türkçe</span></div>`)}</div>`,
  game:()=>`<div class="settings-columns">${card('Ekran','Görüntünün boyutu ve yerleşimi.',`${select('resolution','Sahne çözünürlüğü',[['1280x800','1280 × 800 · 16:10'],['1920x1080','1920 × 1080 · 16:9'],['1080x1920','1080 × 1920 · 9:16']])}${select('windowMode','Pencere biçimi',['Pencere','Kenarlıksız','Tam ekran'])}${select('scaleMode','Farklı ekranlara uyum',['Oranı koru','Ekranı doldur'])}<div class="field-pair">${field('background','Boş alan rengi','color')}${select('fps','Kare hızı',['30','60','120'])}</div>`)}${card('Sahne önizlemesi','Seçtiğin ekran oranı burada görünür.',`<div class="display-preview"><div data-display-frame><span class="preview-moon"></span><span class="preview-hill"></span><div>Mira<br><small>Bir gece, bir ışık</small></div></div></div><div class="preview-caption" data-resolution-preview></div>${select('startScene','Başlangıç sahnesi',[['selected','Seçili node'],['0','Bir gece, bir ışık'],['1','Yol ayrımı'],['2','Yeni bir sabah']])}`)}</div>`,
  story:()=>`<div class="settings-columns">${card('Diyalog görünümü','Metnin biçimi ve okuma hızı.',`${range('textSpeed','Metin hızı',10,60,1,' harf/sn')}${range('textSize','Yazı boyutu',14,28,1,' px')}${select('font','Yazı karakteri',['Sade','Kitap'])}<div class="reading-preview"><span>MIRA</span><p>Gece ne kadar sessiz… Sanki bütün dünya bir şey söylememi bekliyor.</p><small data-reading-speed></small></div>`)}${card('İlerleme ve seçim','Oyuncunun hikâye içinde nasıl ilerleyeceği.',`${toggle('autoAdvance','Otomatik ilerleme','Satır bittikten sonra sonraki diyaloğa geç.')}${range('autoDelay','Satır bekleme süresi',1,6,.5,' sn')}${select('skip','Atlama davranışı',['Yalnız okunmuş metin','Tüm metin'])}${toggle('choiceTimer','Süreli seçimler','Seçenekler için geri sayım göster.')}${field('choiceSeconds','Seçim süresi · saniye','number','min="5" max="60"')}`)}</div>`,
  audio:()=>`<div class="settings-columns">${card('Ses dengesi','Her ses grubunu ayrı ayarla.',`${range('master','Genel ses',0,100)}${range('music','Müzik',0,100)}${range('effects','Efektler',0,100)}${range('voice','Seslendirme',0,100)}`)}${card('Oynatma davranışı','Sahneler arasındaki geçişleri yumuşat.',`<div class="audio-art" aria-label="Ses dengesi görünümü"><svg><use href="#i-audio"/></svg><div>${Array.from({length:15},(_,i)=>`<i style="--bar:${18+(i*23)%64}%"></i>`).join('')}</div><span>Gece ambiyansı</span></div>${toggle('mute','Sessiz başlat','Oyun açılırken sesleri kapalı tut.')}${toggle('backgroundAudio','Arka planda müzik','Başka pencereye geçildiğinde müzik sürsün.')}${range('fade','Müzik geçişi',0,4,.5,' sn')}`)}</div>`,
  input:()=>`<div class="settings-columns">${card('Klavye kısayolları','Bir alana tıklayıp istediğin kısayolu yaz.',`<div class="binding-list">${[['continueKey','Diyaloğa devam et'],['historyKey','Diyalog geçmişi'],['autoKey','Otomatik ilerleme'],['skipKey','Metni atla'],['menuKey','Oyun menüsü'],['quickSaveKey','Hızlı kayıt'],['quickLoadKey','Hızlı yükleme']].map(([key,label])=>`<label><span>${label}</span><input name="${key}" maxlength="20" aria-label="${label} kısayolu"></label>`).join('')}</div>`)}${card('Dokunmatik ve kontrolcü','Aynı eylemler için farklı giriş biçimleri.',`${toggle('tap','Dokunarak devam','Sahneye dokunmak diyaloğu ilerletir.')}${toggle('swipe','Kaydırarak geçmiş','Yukarı kaydırarak önceki satırları aç.')}${toggle('hold','Basılı tutarak atla','Uzun dokunma metni hızlandırır.')}${toggle('gamepad','Kontrolcü desteği','Seçimler arasında yön tuşlarıyla gez.')}<div class="gesture-art"><svg aria-hidden="true"><use href="#i-edit"/></svg><div><strong>Bir dokunuş, bir sonraki cümle.</strong><small>Dokunma bölgeleri sahne boyunca tutarlı kalır.</small></div></div>`)}</div>`,
  save:()=>`<div class="settings-columns">${card('Kayıt düzeni','Oyuncunun hikâyeye geri dönüş yolu.',`<div class="field-pair">${field('slots','Kayıt yuvası','number','min="3" max="30"')}${field('history','Geçmiş satır sayısı','number','min="20" max="500"')}</div>${toggle('autosave','Otomatik kayıt','Hikâye ilerledikçe kaldığın yeri sakla.')}${select('savePoint','Kayıt noktası',['Sahne geçişlerinde','Bölüm sonlarında'])}<div class="save-slot-preview"><svg><use href="#i-moon"/></svg><div><strong>Bir gece, bir ışık</strong><span>Mira · Başlangıç sahnesi</span></div><small>01</small></div>`)}${card('Dil ve okuma','Hikâyeyi rahat ve anlaşılır kıl.',`${select('language','Ana dil',['Türkçe','English','日本語'])}${toggle('english','İngilizce seçeneği','Oyun menüsünde ikinci bir dil göster.')}${toggle('largeText','Büyük metin seçeneği','Oyuncuya daha büyük yazı seçimi sun.')}${toggle('reducedMotion','Hareketi azalt','Arayüz geçişlerini sadeleştir.')}`)}</div>`,
  editor:()=>`<div class="settings-columns">${card('Görünüm','Çalışma alanının tonunu seç.',`${select('theme','Tema',['Gece','Grafit'])}${select('accent','Vurgu rengi',['Kemik','Lavanta','Adaçayı'])}<div class="theme-preview"><div><i></i><i></i><i></i></div><span></span><span></span><span></span></div>`)}${card('Sahne yardımcıları','Düzenlerken görmek istediğin işaretler.',`${toggle('grid','Node ızgarası','Hikâye akışının arkasında noktalı zemin.')}${toggle('guides','Obje çerçeveleri','Edit Scene’de seçimi ve sınırları göster.')}${toggle('snap','Hizalama rehberleri','Objeler arasında hizalama işaretleri.')}${toggle('rulers','Cetveller','Sahne kenarlarında ölçü rehberleri.')}`)}</div>`,
  export:()=>`<div class="settings-columns">${card('Hedef platform','Paket taslağının kullanılacağı yeri seç.',`<div class="platform-options">${['Windows','Linux','macOS','Android'].map(name=>`<label><input type="radio" name="platform" value="${name}"><span>${name==='Android'?'▯':'▱'}</span><strong>${name}</strong></label>`).join('')}</div>${field('packageName','Paket adı','text','maxlength="80"')}${select('compression','Paket boyutu',['Dengeli','Küçük boyut','Yüksek kalite'])}`)}${card('Paket içeriği','Paylaşılacak taslağın kapsamı.',`${toggle('includeMusic','Ses ve müzik','Müzik, efekt ve seslendirme varlıkları.')}${toggle('includeScripts','Lua scriptleri','Kod editöründeki taslak dosyalar.')}${toggle('includeLanguages','Dil seçenekleri','Seçili dil ve çeviri tercihleri.')}<div class="export-summary"><span class="tool-caption">TASLAK ÖZETİ</span><strong data-package-preview></strong><p data-export-preview></p><span class="export-format">Proje taslağı · JSON</span></div>`)}</div>`
};
export function bindSettings(dialog,context){
  let values={...defaults},active='project',draft={...defaults},dirty=false;
  try{const data=JSON.parse(prototypeStorage.getItem('rowl-design-preferences'));if(data&&typeof data==='object')for(const [key,value] of Object.entries(defaults))if(typeof data[key]===typeof value)values[key]=data[key];}catch{}
  function render(){
    const [title,subtitle,description]=headings[active];
    dialog.innerHTML=`<form id="settings-form"><header class="dialog-header"><div><span class="tool-caption">ROWL / AYARLAR</span><h2 id="settings-title">${title}</h2></div><button type="button" class="icon-button" data-dismiss aria-label="Ayarları kapat"><svg><use href="#i-close"/></svg></button></header><div class="settings-nav-shell"><button type="button" class="icon-button settings-nav-step" data-nav-step="-1" aria-label="Önceki ayar bölümleri">‹</button><nav class="settings-nav" aria-label="Ayar bölümleri">${categories.map(([key,label,icon])=>`<button type="button" data-category="${key}" aria-current="${key===active?'page':'false'}"><svg><use href="#i-${icon}"/></svg><span>${label}</span></button>`).join('')}</nav><button type="button" class="icon-button settings-nav-step" data-nav-step="1" aria-label="Sonraki ayar bölümleri">›</button></div><div class="settings-scroll"><div class="settings-intro"><span class="tool-caption">${String(categories.findIndex(([key])=>key===active)+1).padStart(2,'0')} / ${categories.length} BÖLÜM</span><h3>${subtitle}</h3><p>${description}</p></div>${sections[active]()}</div><footer class="dialog-footer"><span class="settings-dirty" data-dirty>${dirty?'Kaydedilmemiş değişiklikler':'Değişiklik yok'}</span><button type="button" class="text-button" data-dismiss>Vazgeç</button><button type="submit" class="primary-button">${active==='export'?'Taslağı indir':'Uygula'}</button></footer></form>`;
    bindFormFeedback(dialog.querySelector('form'));
    for(const input of dialog.querySelectorAll('[name]')){const value=draft[input.name];if(input.type==='checkbox')input.checked=value;else if(input.type==='radio')input.checked=value===input.value;else input.value=value;}
    previews(); updateNav();
    dialog.querySelector('.settings-nav').addEventListener('scroll',updateNav);
  }
  function updateNav(){
    const nav=dialog.querySelector('.settings-nav'), shell=dialog.querySelector('.settings-nav-shell');if(!nav)return;
    const overflow=nav.scrollWidth>shell.clientWidth-28;
    const prev=dialog.querySelector('[data-nav-step="-1"]'), next=dialog.querySelector('[data-nav-step="1"]');
    prev.hidden=next.hidden=!overflow;
    prev.disabled=nav.scrollLeft<=1;next.disabled=nav.scrollLeft+nav.clientWidth>=nav.scrollWidth-1;
    shell.dataset.start=String(!prev.disabled);shell.dataset.end=String(!next.disabled);
  }
  new ResizeObserver(updateNav).observe(dialog);
  function collect(){for(const input of dialog.querySelectorAll('[name]')){if(input.type==='radio'){if(input.checked)draft[input.name]=input.value;}else if(input.type==='checkbox')draft[input.name]=input.checked;else if(input.type==='range'||input.type==='number'){if(input.value!==''&&Number.isFinite(Number(input.value)))draft[input.name]=Number(input.value);}else draft[input.name]=input.value;}}
  function previews(){
    for(const output of dialog.querySelectorAll('[data-output]')){const input=dialog.querySelector(`[name="${output.dataset.output}"]`);output.textContent=`${input.value}${input.dataset.suffix}`;}
    const project=dialog.querySelector('[data-project-preview]');if(project){project.textContent=draft.project||'İsimsiz hikâye';dialog.querySelector('[data-cover-preview]').dataset.cover=draft.cover;}
    const frame=dialog.querySelector('[data-display-frame]');if(frame){const [w,h]=draft.resolution.split('x').map(Number);frame.style.aspectRatio=`${w}/${h}`;frame.parentElement.style.background=draft.background;dialog.querySelector('[data-resolution-preview]').textContent=`${w} × ${h} · ${draft.windowMode}`;}
    const reading=dialog.querySelector('.reading-preview');if(reading){reading.querySelector('p').style.fontSize=`${draft.textSize}px`;reading.querySelector('p').style.fontFamily=draft.font==='Kitap'?'Georgia,serif':'inherit';dialog.querySelector('[data-reading-speed]').textContent=`${draft.textSpeed} harf / saniye`;}
    const art=dialog.querySelector('.audio-art');if(art){art.style.opacity=draft.mute?.3:.3+draft.master/100*.7;}
    const theme=dialog.querySelector('.theme-preview');if(theme){theme.style.background=draft.theme==='Grafit'?'#28282d':'#101013';theme.style.setProperty('--preview-accent',{Kemik:'#e5dfd0',Lavanta:'#bfb4df',Adaçayı:'#b5c6b2'}[draft.accent]);}
    const summary=dialog.querySelector('[data-package-preview]');if(summary){summary.textContent=draft.packageName||'İsimsiz paket';dialog.querySelector('[data-export-preview]').textContent=`${draft.platform} · ${draft.resolution.replace('x',' × ')} · ${draft.language}`;}
  }
  dialog.addEventListener('input',()=>{collect();dirty=true;dialog.querySelector('[data-dirty]').textContent='Kaydedilmemiş değişiklikler';previews();});
  dialog.addEventListener('change',()=>{collect();dirty=true;dialog.querySelector('[data-dirty]').textContent='Kaydedilmemiş değişiklikler';previews();});
  dialog.addEventListener('click',event=>{const step=event.target.closest('[data-nav-step]');if(step){const nav=dialog.querySelector('.settings-nav');nav.scrollBy({left:Number(step.dataset.navStep)*Math.max(160,nav.clientWidth*.7),behavior:document.documentElement.classList.contains('reduce-motion')||matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});return;}if(event.target.closest('[data-dismiss]'))dialog.close();const category=event.target.closest('[data-category]');if(category){collect();active=category.dataset.category;render();const selected=dialog.querySelector('[aria-current=page]');selected.focus({preventScroll:true});selected.scrollIntoView({block:'nearest',inline:'center'});}});
  dialog.addEventListener('submit',event=>{
    event.preventDefault();collect();values={...draft};try{prototypeStorage.setItem('rowl-design-preferences',JSON.stringify(values));}catch{}
    context.apply({project:values.project,resolution:values.resolution,startScene:values.startScene,grid:values.grid,guides:values.guides});
    document.documentElement.classList.toggle('reduce-motion',values.reducedMotion);
    if(active==='export')context.export({...values});dialog.close();
  });
  document.documentElement.classList.toggle('reduce-motion',values.reducedMotion);
  return {snapshot:()=>({...values}),restore:data=>{values={...defaults};if(data&&typeof data==='object')for(const [key,value] of Object.entries(defaults))if(typeof data[key]===typeof value)values[key]=data[key];},open(category){context.beforeOpen();active=category in sections?category:'project';draft={...values,...context.get()};dirty=false;render();dialog.showModal();dialog.querySelector('[aria-current=page]').scrollIntoView({block:'nearest',inline:'center'});}};
}
