using Avalonia;
using Avalonia.Headless;
using RowlEngine.Editor.Services;
using RowlEngine.Editor.ViewModels;
AppBuilder.Configure<Application>().UseHeadless(new AvaloniaHeadlessPlatformOptions()).SetupWithoutStarting();
string work=Path.Combine(Path.GetTempPath(),"rowl-discard-probe-"+Guid.NewGuid().ToString("N"));
var created=ProjectFactory.CreateNewProject("DiscardProbe",work);
if(!created.Success) throw new Exception(created.Error);
string root=created.Info!.Path;
var vm=new MainWindowViewModel(root,connectEngine:false);
vm.Settings.AutoSaveEnabled=false;
if(!vm.SaveProjectNow()) throw new Exception("initial save failed");
string graph=Path.Combine(root,"Assets","json","full_story_graph.json");
string before=File.ReadAllText(graph);
vm.Nodes[0].DialogueText="UNSAVED_DISCARDED_SENTINEL";
vm.ScheduleSave();
string marker=Path.Combine(root,"Assets","json",".recovery","dirty.flag");
Console.WriteLine($"DIRTY_MARKER_BEFORE_DISCARD={File.Exists(marker)}");
bool closeAllowed=EditorProjectLifecycleCoordinator.ResolveUnsavedChangesAsync(()=>Task.FromResult<string?>("discard"),()=>vm.SaveProjectNow(),()=>vm.IsProjectDirty,d=>vm.IsProjectDirty=d).GetAwaiter().GetResult();
Console.WriteLine($"DISCARD_CLOSE_ALLOWED={closeAllowed}");
Console.WriteLine($"VM_DIRTY_AFTER_DISCARD={vm.IsProjectDirty}");
Console.WriteLine($"DIRTY_MARKER_AFTER_DISCARD={File.Exists(marker)}");
vm.Dispose();
string after=File.ReadAllText(graph);
Console.WriteLine($"DISK_CHANGED_AFTER_DISCARD_DISPOSE={before!=after}");
Console.WriteLine($"DISCARDED_EDIT_ON_DISK={after.Contains("UNSAVED_DISCARDED_SENTINEL")}");
Directory.Delete(work,true);
